### PR TITLE
Compilable setting on ROS Indigo.

### PR DESCRIPTION
**Pull request by 130s**
Response to https://github.com/kth-ros-pkg/force_torque_tools/issues/5#issuecomment-92729319

DON'T MERGE into `hydro` branch. I'm afraid the build will likely be to fail on ROS Hydro with this PR. So if someone can create indigo (or similar) branch I'll re-target this PR to the new branch.

Note that I haven't tested with hardware. I simply tried to build on Indigo.

### CODE REVIEW

**Comment by 130s** [comment]
Btw just a note; without this PR build fails on Indigo:

```
$ catkin build
Creating build space directory, '/home/rospasta/cws_tools/build' 
----------------------------------------------------------------------------------------------------------
:                                                                                                                                    
Starting ==> force_torque_sensor_calib                                   
Starting ==> force_torque_tools                                          
Starting ==> gravity_compensation                                        

[force_torque_sensor_calib] ==> '/home/rospasta/cws_tools/build/force_torque_sensor_calib/build_env.sh /usr/bin/cmake /home/rospasta/cws_tools/src/kth-ros-pkg/force_torque_tools/force_torque_sensor_calib -DCATKIN_DEVEL_PREFIX=/home/rospasta/cws_tools/devel -DCMAKE_INSTALL_PREFIX=/home/rospasta/cws_tools/install' in '/home/rospasta/cws_tools/build/force_torque_sensor_calib'
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /home/rospasta/cws_tools/devel
-- Using CMAKE_PREFIX_PATH: /home/rospasta/cws_tools/devel;/opt/ros/indigo
-- This workspace overlays: /home/rospasta/cws_tools/devel;/opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/rospasta/cws_tools/build/force_torque_sensor_calib/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.11
-- Using these message generators: gencpp;geneus;genlisp;genpy
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindEigen.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen" with any of
  the following names:

    EigenConfig.cmake
    eigen-config.cmake

  Add the installation prefix of "Eigen" to CMAKE_PREFIX_PATH or set
  "Eigen_DIR" to a directory containing one of the above files.  If "Eigen"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/rospasta/cws_tools/build/force_torque_sensor_calib/CMakeFiles/CMakeOutput.log".
See also "/home/rospasta/cws_tools/build/force_torque_sensor_calib/CMakeFiles/CMakeError.log".
[force_torque_sensor_calib] <== '/home/rospasta/cws_tools/build/force_torque_sensor_calib/build_env.sh /usr/bin/cmake /home/rospasta/cws_tools/src/kth-ros-pkg/force_torque_tools/force_torque_sensor_calib -DCATKIN_DEVEL_PREFIX=/home/rospasta/cws_tools/devel -DCMAKE_INSTALL_PREFIX=/home/rospasta/cws_tools/install' failed with return code '1'

Failed   <== force_torque_sensor_calib [ 3.5 seconds ]                   Finished <== force_torque_tools        [ 5.0 seconds ]                   
Finished <== gravity_compensation      [ 11.9 seconds ]                  
[build] There were '1' errors:                                           

Failed to build package 'force_torque_sensor_calib' because the following command:

# Command to reproduce:
cd /home/rospasta/cws_tools/build/force_torque_sensor_calib && /home/rospasta/cws_tools/build/force_torque_sensor_calib/build_env.sh /usr/bin/cmake /home/rospasta/cws_tools/src/kth-ros-pkg/force_torque_tools/force_torque_sensor_calib -DCATKIN_DEVEL_PREFIX=/home/rospasta/cws_tools/devel -DCMAKE_INSTALL_PREFIX=/home/rospasta/cws_tools/install; cd -

# Path to log:
cat /home/rospasta/cws_tools/build/build_logs/force_torque_sensor_calib.log

Exited with return code: 1 
[build] Runtime: 12.0 seconds 
```

**Comment by fevb** [comment]
Thanks a lot for this @130s ! I'll open an `indigo` branch so that we can merge

**Comment by fevb** [comment]
@130s : I've opened an [indigo branch](https://github.com/kth-ros-pkg/force_torque_tools/tree/indigo), could you please redirect your PR to that branch ? Thanks!

**Comment by 130s** [comment]
All right, looks like I just have to open a new PR in order to target a new branch.

**Pull request closed without merging**
